# Generated by Django 5.1.2 on 2024-10-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytrade',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='daytrade',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='perminutetrade',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='perminutetrade',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='data_path',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='name',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
